### ISSUE TITLE
Interact with app inputs during tour

### ISSUE THREAD

**Issue by marcusyoung** [etiennebacher/conductor#53]
Hi,

Is it possible to interact with inputs during the tour, for example select a checkbox, or select a drop-down etc.. ?

Thanks

Marcus

**Comment by etiennebacher** [comment]
Hi, there are two ways you can interact with elements during the tour:

* the element is highlighted (this means you can only interact with this element)
* use `useModalOverlay = FALSE` when you create the tour (see example below). However, this will remove the grey overlay on the whole tour

Here, I disable the overlay and I can interact with the button at any step of the tour, not only when it's highlighted:
```r
library(shiny)
library(conductor)

conductor <- Conductor$
  new(useModalOverlay = FALSE)$ # <<<<<<<<<<<<<<<< here
  step(
    title = "Hello there",
    text = "This popover is displayed in the center of the screen."
  )$
  step(
    "This is a button",
    "This button has no purpose. Its only goal is to serve as support for demo.",
    "#mybutton"
  )$
  step(
    ".to-highlight",
    title = "This is some text",
    text = "Only the first p tag is highlighted."
  )



ui <- fluidPage(
  useConductor(),
  actionButton("mybutton", "Test"),
  br(),
  div(class = "to-highlight", p("Hello, I'm the first p tag")),
  div(class = "to-highlight", p("Hi, I'm the second p tag"))
)

server <- function(input, output, session){
  conductor$init()$start()
  
  observeEvent(input$mybutton, print("hi there"))
}

shinyApp(ui, server)
```
Is this what you were looking for? If not, can you provide a more detailed example?

**Comment by marcusyoung** [comment]
Hi,

I probably didn't explain very well. I don't want the user to interact with the inputs but the tour itself to trigger inputs. Aspects of the app aren't visible unless actions take place such as clicking on a map, selecting options in a dropdown and so on. This is probably something much more advanced thank the package is intended for. I may be better to just do a short video tour.

Thanks

Marcus

**Comment by etiennebacher** [comment]
You can trigger some elements with the tour steps by using an `id` in `$step()` and then use the value of `$getCurrentStep()` to trigger something. Here's an example where the third step triggers the plot rendering (and highlights it at the same time).

```r
library(shiny)
library(conductor)

conductor <- Conductor$
  new()$ 
  step(
    title = "Hello there",
    text = "This popover is displayed in the center of the screen."
  )$
  step(
    "This is a button",
    "The next step will trigger the plot rendering",
    "#mybutton"
  )$
  step(
    title = "here's the plot",
    text = "",
    "#testplot",
    id = "show_plot"
  )

ui <- fluidPage(
  useConductor(),
  actionButton("mybutton", "Test"),
  br(),
  plotOutput("testplot")
)

server <- function(input, output, session){
  conductor$init()$start()
  
  observe({
    if (isTRUE(conductor$getCurrentStep() == "show_plot")) {
      output$testplot <- renderPlot(plot(mtcars))
    }
  })
}

shinyApp(ui, server)
```
If it's not what you want, please add a small example so that I have a better idea of what you're looking for :)

**Comment by etiennebacher** [comment]
@marcusyoung does my last comment solve your problem?

**Comment by marcusyoung** [comment]
I think it will, yes. I've not had chance to try it yet.

**Comment by etiennebacher** [comment]
@marcusyoung please reopen if the problem is still there
